version: '2.2'

services:
    terraform:
        build:
          context: hetzner
          args:
            - VCS_REF="0.1"
        entrypoint: make
        command: 
           - entrypoint.sh
        volumes:
           - ./terraform:/terraform
           - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
           #- $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
           #- ~/.ssh/id_ed25519.pub:~/.ssh/id_ed25519.pub
           #- ~/.ssh/id_ed25519:~/.ssh/id_ed25519
        env_file: .env
        #environment:
           #- SSH_AUTH_SOCK
        working_dir: /terraform
